spring:
  application:
    name: favorite-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/favorite_db?createDatabaseIfNotExist=true
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    jpa:
      repositories:
        enabled: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
server:
  port: 11000