services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mariadb:
    image: "mariadb"
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_ROOT_USER=root

  mongodb:
    image: "mongo"
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always

  travelling-app-be:
    build: ./travelling-app-be
    container_name: travelling-app-be
    ports:
      - "8761:8761"
    restart: always

  admin-service:
    build: ./travelling-app-be/admin-service
    container_name: admin-service
    ports:
      - "9000:9000"
    restart: always
    depends_on:
      - travelling-app-be
      - kafka
      - mariadb
      - mongodb

  authen-service:
    build: ./travelling-app-be/authen-service
    container_name: authen-service
    ports:
      - "13000:13000"
    restart: always
    depends_on:
      - travelling-app-be
      - kafka
      - mariadb
      - mongodb
      - admin-service

  travelling-service:
    build: ./travelling-app-be/travelling-service
    container_name: travelling-service
    ports:
      - "10000:10000"
    restart: always
    depends_on:
      - travelling-app-be
      - kafka
      - mariadb
      - mongodb
      - admin-service

  favorite-service:
    build: ./travelling-app-be/favorite-service
    container_name: favorite-service
    ports:
      - "11000:11000"
    restart: always
    depends_on:
      - travelling-app-be
      - kafka
      - mariadb
      - mongodb
      - admin-service
      - travelling-service

  booking-service:
    build: ./travelling-app-be/booking-service
    container_name: booking-service
    ports:
      - "12000:12000"
    restart: always
    depends_on:
      - travelling-app-be
      - kafka
      - mariadb
      - mongodb
      - admin-service

  ai-service:
    build: ./travelling-app-be/ai-service
    container_name: ai-service
    ports:
      - "14000:14000"
    restart: always
    depends_on:
      - travelling-app-be
      - kafka
      - mariadb
      - mongodb
      - admin-service

  api-gateway-service:
    build: ./travelling-app-be/api-gateway-service
    container_name: api-gateway-service
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - admin-service
      - authen-service
      - travelling-service
      - favorite-service
      - booking-service
      - ai-service
      - travelling-app-be
      - kafka
  mobile-fe:
    build: ./travelling-app-fe
    container_name: mobile-fe
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - api-gateway-service
