spring:
  application:
    name: api-gateway-service
  main:
    web-application-type: reactive
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://travelling_app_be:8761/eureka/
server:
  port: 8080