spring:
  application:
    name: authenticate-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/authen_db?createDatabaseIfNotExist=true
    username: root
    password: 123456789
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        enabled: true
server:
  port: 13000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
aws_access_key: AKIA2KKFZ2FFVNGA53QB
aws_secret_key: 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
