spring:
  application:
    name: travelling-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/travelling-db?createDatabaseIfNotExist=true
    username: root
    password: 123456789
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      database: travelling-db
      host: localhost
      port: 27017
server:
  port: 10000
eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
